replicas: 1

plugins:
  - grafana-piechart-panel

persistence:
  enabled: true
  initChownData: true
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  size: 4Gi
  # annotations: {}
  # subPath: ""
  # existingClaim:

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  labels: {}
  path: /
  hosts:
    - grafana.axs-labs.com
  tls:
  - hosts:
    - grafana.axs-labs.com
    secretName: letsencrypt-grafana

grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    root_url: https://grafana.axs-labs.com
